- name: variables to print
  hosts: web
  vars: # This is play-level, all tasks in this play have access to this variables
    COURSE: "Devops with AWS"
    DURATION: "120HRS"
    TRAINER: "Amarnath Gotru"
  tasks:
  - name: print the information
    vars:
      COURSE: "Devops with Azure" # Task level-limited to that particular task
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}} Duration is: {{DURATION}} and trainer is: {{TRAINER}}"