- name: Import variables from files
  hosts: web
  vars_files:
  -vars.yaml
  tasks:
  - name: import vars from files
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}} Duration is: {{DURATION}} and trainer is: {{TRAINER}}"