- name: passing variables through prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
  - name: DURATION
    prompt: enter the duration of course
  - name: TRAINER
    prompt: trainer name
  tasks: 
  - name: print the course information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}} Duration is: {{DURATION}} and trainer is: {{TRAINER}}"