- name: check a number if it is less than 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: please enter the number
    private: false
  tasks:
  - name: print this number if it is less than 10
    ansible.builtin.debug:
      msg: "given number {{ number }} is less than 10"
    when: number | int < 10
  
  - name: print this number if it is greater than or equal to 10
    ansible.builtin.debug:
      msg: "given number {{ number }} is greater than or equal to 10"
    when: number | int >= 10

