- name: check a number if it is less than 50 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: number
    prompt: please enter the number
    private: false
  tasks:
  - name: print this number if it is less than 50
    ansible.builtin.debug:
      msg: "given number {{ number }} is less than 50"
    when: number | int < 50
  
  - name: print this number if it is greater than 50
    ansible.builtin.debug:
      msg: "given number {{ number }} is greater than 50"
    when: number | int > 50

  - name: print this number if it is equal to 50
    ansible.builtin.debug:
      msg: "given number {{ number }} is equal to 50"
    when: number | int = 50

