- name: Filters/Functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variable
    ansible.builtin.debug:
      msg: "Hello {{ course | default ('ansible') }}"
  
  - name: print the name 
    ansible.builtin.debug:
      msg: "Hello {{ name }}"