- name: usage of upper function
  hosts: local
  connection: local
  vars:
    greeting: "Hello amarnath"
  tasks:
  - name: convert string into uppercase
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: convert string into lowercase
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"