- name: converting dictionary/map into list
  hosts: local
  connection: local
  vars:
    course:
      name: devops with aws
      duration: 120hrs
      trainer: amarnath

    course2:
    - {"key": "name","value": "devops with aws"}
    - {"key": "duration","value": "120hrs"}
    - {"key": "trainer","value": "amarnath"}

  tasks:
  - name: convert map into list
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"

  - name: convert list into map
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"
      