- name: converting dictionary/map into list
  hosts: local
  connection: local
  vars:
    course:
      name: devops with aws
      duration: 120hrs
      trainer: amarnath
  tasks:
  - name: convert map into list
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"